import express from "express";
import dotenv from "dotenv";
import authRoutes from "./routes/authRoutes.js";
import convertRoutes from "./routes/convertRoutes.js";
import pdfCompressRoutes from "./routes/pdfCompressRoutes.js";
dotenv.config();

import connectDB from "./config/db.js";
import healthRoutes from "./routes/healthRoutes.js";
import splitExtractRoutes from "./routes/Split_Extract_Routes.js";
import pdfRoutes from "./routes/pdfRoutes.js";
import rotateRoutes from "./routes/rotateRoutes.js";
import organizeRoutes from "./routes/organizeRoutes.js";
import ocrRoutes from "./routes/ocrRoutes.js";
import wordToPdfRoutes from "./routes/wordToPdfRoutes.js";
import excelToPdfRoutes from "./routes/excelToPdfRoutes.js";
import htmlToPdfRoutes from "./routes/htmlToPdfRoutes.js";
import removePagesRoutes from "./routes/removePagesRoutes.js";
import jpgToPdfRoutes from "./routes/jpgToPdfRoutes.js";
import pngToPdfRoutes from "./routes/pngToPdfRoutes.js";
import pdfToWordRoutes from "./routes/pdfToWordRoutes.js";
import pdfToExcelRoutes from "./routes/pdfToExcelRoutes.js";
import pdfToPptRoutes from "./routes/pdfToPptRoutes.js";
import pdfWatermarkRoutes from "./routes/pdfWatermarkRoutes.js";
import pdfCropRoutes from "./routes/pdfCropRoutes.js";
import pdfEditRoutes from "./routes/pdfEditRoutes.js";
import pdfTopngRoutes from "./routes/pdfTopngRoutes.js";
import pdfToJpgRoutes from "./routes/pdfToJpgRoutes.js";
import pdfRedactRoutes from "./routes/pdfRedactRoutes.js";
import pdfCompareRoutes from "./routes/pdfCompareRoutes.js";
import protectRoutes from "./routes/protectRoutes.js";
import unlockRoutes from "./routes/unlockRoutes.js";
import signRoutes from "./routes/signRoutes.js";
import pdfPageNumbersRoutes from "./routes/pdfPageNumbersRoutes.js";
import aiChatRoutes from "./routes/aiChatRoutes.js";
import summarizeRoutes from "./routes/summarizeRoutes.js";
import explainRoutes from "./routes/explainRoutes.js";
import translateRoutes from "./routes/translateRoutes.js";
import aiExtractRoutes from "./routes/aiExtractRoutes.js";
import aiGenerateRoutes from "./routes/aiGenerateRoutes.js";
import uploadRoutes from "./routes/uploadRoutes.js";
import downloadRoutes from "./routes/downloadRoutes.js";
import jobRoutes from "./routes/jobRoutes.js";
import jobHistoryRoutes from "./routes/jobHistoryRoutes.js";
import { errorHandler } from "./middleware/errorMiddleware.js";

const app = express();

app.use(express.json());
app.use("/uploads", express.static("uploads"));

connectDB();

app.use("/", healthRoutes);
app.use("/api/pdf", splitExtractRoutes);
app.use("/api/pdf", pdfRoutes);
app.use("/api/pdf", rotateRoutes);
app.use("/api/pdf", organizeRoutes);
app.use("/api/pdf", ocrRoutes);
app.use("/api/pdf", removePagesRoutes);
app.use("/api/pdf", protectRoutes);
app.use("/api/pdf", unlockRoutes);
app.use("/api/pdf", signRoutes);
app.use("/api", wordToPdfRoutes);
app.use("/api", excelToPdfRoutes);
app.use("/api", htmlToPdfRoutes);
app.use("/api/auth", authRoutes);
app.use("/api/convert", convertRoutes);
app.use("/api/convert", jpgToPdfRoutes);
app.use("/api/convert", pngToPdfRoutes);
app.use("/api/convert", pdfToWordRoutes);
app.use("/api/convert", pdfToExcelRoutes);
app.use("/api/convert", pdfToPptRoutes);
app.use("/api/convert", pdfTopngRoutes);
app.use("/api/convert", pdfToJpgRoutes);
app.use("/api/pdf", pdfCompressRoutes);
app.use("/api/pdf", pdfWatermarkRoutes);
app.use("/api/pdf", pdfCropRoutes);
app.use("/api/pdf", pdfEditRoutes);
app.use("/api/pdf", pdfRedactRoutes);
app.use("/api/pdf", pdfCompareRoutes);
app.use("/api/pdf", pdfPageNumbersRoutes);
app.use("/api/ai", aiChatRoutes);
app.use("/api/ai", summarizeRoutes);
app.use("/api/ai", explainRoutes);
app.use("/api/ai", translateRoutes);
app.use("/api/ai", aiExtractRoutes);
app.use("/api/ai", aiGenerateRoutes);
app.use("/api/files", uploadRoutes);
app.use("/api/files", downloadRoutes);
app.use("/api", jobRoutes);
app.use("/api", jobHistoryRoutes);
app.use(errorHandler);

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
